### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by kingthorin** [timaschew/link-checker#10]
I was setting this up for use in a GitHub action, it seems that `mkdirp` isn't included as a dependency but should be:

```console
link-checker ./index.html --external-only --http-status-ignore 301 302 --url-ignore .*linkedin.*
 Error: Cannot find module 'mkdirp'
Require stack:
- /usr/local/lib/node_modules/link-checker/link-checker.js
- /usr/local/lib/node_modules/link-checker/cli
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/link-checker/link-checker.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
```

I ended up also installing the dependency in order to get the action working:

```yml
on:
  push:

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install Dependencies
        run: |
          npm install -g mkdirp
          npm install -g link-checker
      - name: Get Page
        # wget saves as index.html
        run: wget https://example.org/resourcetocheck/
      - name: Check Links
        run: link-checker ./index.html --external-only --http-status-ignore 301 302 --url-ignore .*linkedin.*
```
